# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: TestingApi-deployment 
  namespace: TestingApi
  labels:
    app: TestingApi-deployment
spec:
  selector:
    matchLabels:
      app: TestingApi-deployment
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  TestingApi-deployment
      labels:
        app: TestingApi
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: TestingApi
        image: asskit/testing_api:latest
        imagePullPolicy: IfNotPresent 
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - name: web
          containerPort: 8080
---

