kind: Deployment
apiVersion: apps/v1
metadata:
  name: testing-api-deployment
  namespace: testing-api
  labels:
    app: testapi
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
        - name: test-api
          image: asskit/testing_api:535f4381d2f05b3b0c428d3f415e9298bc515243
          ports:
          - name: web
            containerPort: 8080
