name: Create Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'New Tag Name'
        required: true
        type: string
      build_docker_hub:
        description: 'Do you want to publish to DockerHub'
        required: true
        type: boolean
        default: true
    
jobs:
  kuberneties_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout # checkout your sources file
        uses: actions/checkout@v4

      - name: Update values.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.template.spec.containers[0].image = "ghcr.io/notliam99/testingapi:${{ inputs.tag_name }}"' './kuberneties/1-deployment.yaml'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "[Kuberneties Image Update]: (Tag) = ${{ inputs.tag_name }}"
          commit-message: "[Kuberneties Image Update]: (Tag) = ${{ inputs.tag_name }}"
          body: |
            # Kuberneties image update
            This is a automated image updater for tag creations.

            ### Important notes
            on merge of this pull request it will form a new tag and refresh the web deployment.
          branch: CreateTag_${{ inputs.tag_name }}
          labels: |
            enhancement
            Automated Image Update
          base: main
          token: ${{ secrets.PAT }}

      - name: save-dockerHub-OPT
        uses: action-pack/set-variable@v1
        with:
          name: 'BUILD_DOCKER_HUB'
          value: '${{ inputs.build_docker_hub }}'
          token: ${{ secrets.PAT }}

      - name: save-tag_name-OPT
        uses: action-pack/set-variable@v1
        with:
          name: 'NEW_TAG_NAME'
          value: '${{ inputs.tag_name }}'
          token: ${{ secrets.PAT }}

