name: Create Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'New Tag Name'
        required: true
        type: string
      build_docker_hub:
        description: 'Do you want to publish to DockerHub'
        required: true
        type: boolean
        default: true
    
jobs:
  kuberneties_update:
    needs: build-docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:     
      - name: Checkout # checkout your sources file
        uses: actions/checkout@v4

      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'kube/1-deployment.yaml'
          propertyPath: 'spec.template.spec.containers.0.image'
          value: '${{ github.REPO }}/notes:${{ inputs.tag_name }}'
          commitChange: false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "[Kuberneties Image Update]: (Tag) = ${{ inputs.tag_name }}"
          commit-message: "[Kuberneties Image Update]: (Tag) = ${{ inputs.tag_name }}"
          body: |
            # Kuberneties image update
            This is a automated image updater for tag creations.
          branch: CreateTag_${{ inputs.tag_name }}
          labels: |
            enhancement
            Automated Pull Request

      - name: save-dockerHub-OPT
        run: $BUILD_DOCKER_HUB = "${{ inputs.build_docker_hub }}"

      - name: save-tag_name-OPT
        run: $NEW_TAG_NAME = "${{ inputs.tag_name }}"
