name: cross-compile
run-name: ${{ github.actor }}'s rust compile
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: testing_api
            name: testing_api-Linux-x86_64.tar.gz
            command: build
            path: target/x86_64-unknown-linux-gnu/release

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: testing_api.exe
            name: testing_api-Windows-x86_64.zip
            command: both
            path: target/x86_64-pc-windows-msvc/release

          - release_for: MacOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: testing_api
            name: testing_api-Darwin-x86_64.tar.gz
            command: both
            path: target/x86_64-apple-darwin/release
            # more release targets here ...

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Get Binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.release_for }}
          path: ${{ matrix.platform.path }}/${{ matrix.platform.bin }}
          compression-level: 9
          overwrite: true
